const themes = [
  { label: "rjv-default", value: "rjv-default" },
  { label: "apathy", value: "apathy" },
  { label: "ashes", value: "ashes" },
  { label: "brewer", value: "brewer" },
  { label: "bright", value: "bright" },
  { label: "chalk", value: "chalk" },
  { label: "colors", value: "colors" },
  { label: "eighties", value: "eighties" },
  { label: "flat", value: "flat" },
  { label: "google", value: "google" },
  { label: "grayscale", value: "grayscale" },
  { label: "harmonic", value: "harmonic" },
  { label: "hopscotch", value: "hopscotch" },
  { label: "isotope", value: "isotope" },
  { label: "marrakesh", value: "marrakesh" },
  { label: "monokai", value: "monokai" },
  { label: "ocean", value: "ocean" },
  { label: "paraiso", value: "paraiso" },
  { label: "pop", value: "pop" },
  { label: "railscasts", value: "railscasts" },
  { label: "rjv-default-dark", value: "rjv-default-dark" },
  { label: "shapeshifter", value: "shapeshifter" },
  { label: "solarized", value: "solarized" },
  { label: "summerfruit", value: "summerfruit" },
  { label: "tomorrow", value: "tomorrow" },
  { label: "tube", value: "tube" },
  { label: "twilight", value: "twilight" },
  { label: "vibrant-ink", value: "vibrant-ink" },
  { label: "zenburn", value: "zenburn" },
];

export default themes;
